apiVersion: apps/v1
kind: Deployment
metadata:
  name: learners-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learners-api
  template:
    metadata:
      labels:
        app: learners-api
    spec:
      containers:
      - name: learners-api
        image: {{ .Values.backend.image }}
        env:
        # JDBC persistence:
        - name: spring.datasource.url
          valueFrom:
            secretKeyRef:
              name: mysecrets
              key: url
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: mysecrets
              key: username
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: mysecrets
              key: password
        ports:
        - containerPort: 8080
