apiVersion: apps/v1
kind: Deployment
metadata:
  name: learners-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learners-frontend
  template:
    metadata:
      labels:
        app: learners-frontend
    spec:
      containers:
      - name: learners-frontend
        image: {{ .Values.frontend.image }}
        # env:
        # - name: VITE_API_BASE_URL
        #   value: http://localhost:8080
        ports:
        - containerPort: 80
