apiVersion: apps/v1
kind: Deployment
metadata:
  name: learners-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learners-api
  template:
    metadata:
      labels:
        app: learners-api
    spec:
      containers:
      - name: learners-api
        image: shenukacj/learners-api:1.0.0
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: demo-pvc
